version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "9080:80"
        volumes:
            - ./code:/www/htdocs
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./code:/www/htdocs
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
