version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "9080:80"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php:rw
        networks:
            - code-network
    php:
        image: php:fpm
        container_name: php-fpm
        volumes:
            - ./htdocs:/www/htdocs
        networks:
            - code-network
        user: "$UID"

networks:
    code-network:
        driver: bridge
